# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - uses: actions/cache@v2.1.4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B -Dchangelist=-${{github.run_number}} package

    - name: Extract version
      run: |
        VERSION=$(cat pom.xml | grep '<revision' | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')
        echo "VERSION=${VERSION}-${{github.run_number}}" > target/version.txt

    - name: Upload plugin
      uses: actions/upload-artifact@v2.2.2
      with:
        name: gitea
        path: |
          target/gitea.hpi
          target/version.txt

  release:
    needs: [build]
    
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download plugin
        uses: actions/download-artifact@v2.0.8
        with:
          name: gitea
          path: .

      - name: create tag
        run: |
          ls -la
          cat version.txt
    