# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B -Dchangelist=-${{github.run_number}} package

      - name: Extract version
        run: |
          VERSION=$(cat pom.xml | grep '<revision' | grep -o -E '[0-9]+\.[0-9]+(\.[0-9]+)?')
          echo "${VERSION}-${{github.run_number}}" > target/version.txt

      - name: Upload plugin
        uses: actions/upload-artifact@v2.2.2
        with:
          name: gitea
          path: |
            target/gitea.hpi
            target/version.txt

  release:
    needs: [build]

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download plugin
        uses: actions/download-artifact@v2.0.8
        with:
          name: gitea
          path: .

      - name: Create git tag
        run: |
          v=$(cat version.txt)
          git tag v$v
          git push origin v$v
          echo "VERSION=${v}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: gitea.hpi
          name: ${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          body: Relase v${{ env.VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
